[package]
name = "multimesh"
version = "0.0.1"
authors = ["Leo Schwarz <mail@leoschwarz.com>"]

[dependencies]
failure = "0.1"
lazy_static = "1.0"
nalgebra = "0.16"
regex = "1.0"
prettytable-rs = "0.8"
